name: fedscale-11
channels:
  - main
  - conda-forge
dependencies:
  - python=3.7
  - tensorboard
  - numba=0.49.1
  - pip=20.0.2
  - resampy=0.3.1
  - pip:
    - transformers
    - scipy==1.4.1
    - matplotlib==3.1.3
    - torch_baidu_ctc==0.3.0
    - tensorboardX==2.1
    - python-levenshtein==0.12.0
    - pandas==1.1.0
    - PyYAML
    - sox==1.3.7
    - grpcio==1.40.0
    - gym
    - jupyter
    - pillow==9
    - sentencepiece
    - gdown
    - h5py
    - librosa==0.7.2
